name: Test oracle-actions/configure-kubectl-oke

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/configure-kubectl-for-oke.yml"
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/configure-kubectl-for-oke.yml"

jobs:
  sanity-test-configure-kubectl:
    runs-on: ubuntu-latest
    name: Sanity test configuring kubectl for OKE
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Check kubectl path and version
        run: |
          which kubectl
          kubectl version

      - name: Run kubectl in US region
        run: kubectl get nodes -A
