name: Test oracle-actions/get-ocir-repository and oracle-actions/login-ocir

on:
  workflow_dispatch:
  pull_request:
    branches:
      "main"
    paths:
      - ".github/workflows/get-ocir-repository-and-login-ocir.yml"
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/get-ocir-repository-and-login-ocir.yml"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  sanity-test:
    runs-on: ubuntu-latest
    name: Sanity test get-ocir-repository and login-ocir actions
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:

      - name: Retrieve the OCID of a named compartment in tenancy
        uses: oracle-actions/run-oci-cli-command@v1.2.0
        id: find-compartment-id
        with:
          command: 'iam compartment list --compartment-id-in-subtree=true'
          query: "data[?name=='github-actions'].id"

      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: oraclelinux
          compartment: ${{ steps.find-compartment-id.outputs.raw_output }}

      - name: Show OCIR repository path
        id: show-ocir-repository-path
        run: |
          echo "${{ steps.get-ocir-repository.outputs.repo_ocid }}"
          echo "${{ steps.get-ocir-repository.outputs.repo_path }}"

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Tag and push a container image
        id: tag-and-push-image
        run: |
          docker pull oraclelinux:8-slim
          docker tag "oraclelinux:8-slim" "${{ steps.get-ocir-repository.outputs.repo_path }}:8-slim"
          docker push "${{ steps.get-ocir-repository.outputs.repo_path }}:8-slim"
