name: Repository Dispatch

on: [repository_dispatch]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received."
