name: Repository Dispatch

on: [repository_dispatch]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from ${{ github.event.client_payload.repository.full_name }}."
          echo "---"
          echo "Release Tag: ${{ github.event.client_payload.release.tag_name }}"
          echo "Download URL: ${{ github.event.client_payload.release.url }}"
